### ISSUE TITLE
Encode spaces in file names with %20 not +

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/dlss-wowza#28] opened 2016-07-14 00:47 UTC
The path segment of a URI should not have their spaces encoded as a `+` (and use a `%20` instead) since rfc3986 does not indicate that `+` should be handled in any special way (other than literally as a `+`).  This is unlike URL [query parameters](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1) which specifies that spaces are to be replaced by `+`.

We should change the file name portion of the `verify_token` request to encode spaces as `%20` and not `+` which will be handled by the verification code properly.

**Comment by jmartin-sul** [comment] 2016-07-19 20:54
there are issues in practice, possibly due to not deploying new dependencies for the plugin

**Comment by ndushay** [comment] 2016-07-19 21:46
SAR-3198  asks for help in figuring out how to deploy the guava and commons-validator  jars.

**Comment by ndushay** [comment] 2016-07-21 18:10
See #30 for jar deployment work

**Comment by ndushay** [comment] 2016-07-22 00:27
#31 was PR to build a tar containing dlss-wowza jar and its dependencies.  That has been merged, a new release was done and I confirmed it worked afterwards. I updated the jenkins build to create the tar, and it works (the tar is now the artifact). SAR-3198 has the details of what needs to happen to puppet code to get this deployable.

**Comment by ndushay** [comment] 2016-07-26 00:41
SAR-3198 has been taken care of (thanks @kamchan );  this fix has been deployed to -stage.  Perhaps the only thing that remains is for @jmartin-sul  to affirm that media files with spaces and pluses in the file names work???

**Comment by ndushay** [comment] 2016-07-26 00:56
Seems to be an improvement.  Closing in favor of sul-dlss/sul-embed#578.

**Comment by ndushay** [comment] 2016-07-26 00:56
(for reference, see:  https://consul.stanford.edu/display/chimera/Character+set+constraints+for+SDR+file+names  )

**Closed as completed by ndushay** 2016-07-26 00:56 UTC
Labels: bug, media
